import { Geist, Geist_Mono, Caladea } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Layoutwrapper from "@/Component/Layout/Layoutwrapper";
import CartDrawer from "@/Component/CartDrawer";
import Whatsapp from "@/Component/Whatsapp"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const caladea = Caladea({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-caladea",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${caladea.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: "#111827",
              color: "#fff",
              borderRadius: "10px",
            },
          }}
        />

        <Layoutwrapper>
          <Whatsapp/>
          {children}
        </Layoutwrapper>

        <CartDrawer />
      </body>
    </html>
  );
}